### ISSUE TITLE
libVLC as a Media Decoder

### ISSUE THREAD

**Issue by infogulch** [mjibson/moggio#47]
Have you considered using libVLC [0] as a media decoder? It accepts many, many formats and should be able to be built on almost any architecture/os. There are (admittedly old) Go bindings at jteeuwen/go-vlc [1].

0: https://wiki.videolan.org/LibVLC/
1: https://github.com/jteeuwen/go-vlc

**Comment by mjibson** [comment]
I try to avoid using C as much as possible because I don't have a windows build chain with a C compiler, which means windows users don't get that feature, and it makes static compilation more difficult.

**Comment by infogulch** [comment]
That's quite understandable. I just wanted to make you aware of it if you didn't know. :)
